%% This button initializes and brings up the help box for instructions, FAQ, and contact info
function [] = Help_Button(varargin) %Help Button
SCR = get(0,'Screensize');
HB.fh=figure('numbertitle','off',...
              'menubar','none',...
              'units','pixels',...
              'position',[SCR(3)/2-200 ,SCR(4)/2-200 , 430, 550],...
              'name','Help Box',...
              'resize','off');
HB.tg(1) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[5 500 80 40],...
                    'string','General',...
                    'val',1);
HB.tg(2) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[85 500 80 40],...
                    'string','Load File',...
                    'value',0,...
                    'enable','on');
HB.tg(3) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[165 500 80 40],...
                    'string','Side Graphs',...
                    'value',0,...
                    'enable','on');
HB.tg(4) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[245 500 90 40],...
                    'string','Check Boxes',...
                    'value',0,...
                    'enable','on');
HB.tg(5) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[335 500 90 40],...
                    'string','Draw Area Tool',...
                    'value',0,...
                    'enable','on');
HB.tg(6) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[5 460 80 40],...
                    'string','Change to Zero',...
                    'value',0,...
                    'enable','on');
HB.tg(7) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[85 460 80 40],...
                    'string','Sum Selected',...
                    'value',0,...
                    'enable','on');
HB.tg(8) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[165 460 80 40],...
                    'string','Recalculate CoP',...
                    'value',0,'fontsize',7,...
                    'enable','on');
HB.tg(9) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[245 460 90 40],...
                    'string','Navigation',...
                    'value',0,...
                    'enable','on');
HB.tg(10) = uicontrol('style','toggle',...
                    'units','pixels',...
                    'position',[335 460 90 40],...
                    'string','Export Data',...
                    'value',0,...
                    'enable','on');
                
HB.tx(1) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','on',...
                 'string',{' ','This program is designed to visualize',...
                 'and analyze pressure plate data from',...
                 ' text files originating from '... 
                 'Novel Emed Pressure Plate Software.'...
                 '',' ',...
                 'Program designed and edited by'...
                 'Daniel Gibbons. Project overseen by Dr. Nathan Thompson.',' ','If there are '...
                 'any questions not answered by this guide, please send any inquiries to'...
                 'danegibbons@gmail.com or nthomp03@nyit.edu'...
                 'or call (631)456-7733.'},...
                 'fontsize',12,'fontweight','bold');
HB.tx(2) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','The Load File button opens up a window for the'...
                 'user to select their data file in .txt format. The program then'...
                 'reads the contents of the file into a variable as ASCII numbers'...
                 'and parses through it, extracting the amount of frames,',...
                 'frame limits, data matrix, MPP data, MVP data, and center of pressure matrix.'...
                 ' ','The program will then automatically graph the first frame of',...
                 'data with the center of pressure line on top, the current',...
                 'center of pressure of the current frame as a red star, and the',...
                 'weight text turned off.',' ',...
                 'The user may choose to reload another .txt file with the same',... 
                 'button and the process will repeat. If any further steps',... 
                 'have been taken however, it is highly recommended that the',...
                 'user close the GUI and start it again.',' ',...
                 'The total amount of frames included in the data file will display'...
                 'on the bottom right of the Data Extraction and',...
                 'Visualization section for reference.'},...
                 'fontsize',10,'fontweight','bold');
HB.tx(3) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','Side Graphs refers to the Total Force Graph, the'...
                 'Peak Pressure Graph, the MPP Graph, and the MVP Graph.',' ',...
                 'Selecting the Total Force button will create a separate'...
                 'figure on which the total force across all frames is graphed.'...
                 'Selecting the Peak Pressure button performs the same',... 
                 'process as the Total Force button, graphing Peak Pressure',... 
                 'across all frames instead of the Total Force.',...
                 'These graphs may be changed if the user utilizes the',...
                 '''Draw Area Tool'', changes the masked coordinates to zero,',...
                 'and recalculates the Center of Pressure matrix.',' ',...
                 'The Display MPP tool graphs the Maximum Pressure Picture',...
                 'on the same figure the framewise pressure data is graphed'...
                 'on. This is because the data may be used with the weight',...
                 'text and draw area tools.',...
                 ' ','The Display MVP tool behaves in the same manor as the'...
                 'Display MPP tool, graphing instead the Mean Value Pressure.',...
                 'This graph also yields the same functionality with respect',... 
                 'to the analysis tools.'},...
                 'fontsize',10,'fontweight','bold');
HB.tx(4) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','The Check Boxes consist of two separate toggle options:'...
                 ' ','1. Turning on and off Weight Text','&',...
                 '2. Turning on and off the Center of Pressure mapping line',' ',...
                 'PLEASE TAKE NOTE: The Weight Text is intentionally not set'... 
                 'on by default because it slows all other processes down',...
                 'considerably. Only toggle the Weight Text on when you are'...
                 'planning on analyzing a single frame of data for specific numerical information.'... 
                 ' ','The weight text labels each singular cell with its pressure data'...
                 'in kPa. The numbers correspond with the color bar on the far',...
                 'right of the figure.',' ',...
                 'The Center of Pressure check box toggles on and off the'... 
                 'visibility of the center of pressure line and current mapped',...
                 'center of pressure. The current center of pressure will',... 
                 'change from frame to frame but the path the center of',...
                 'pressure traces will stay the same unless recalculated.'},...
                 'fontsize',10,'fontweight','bold');
HB.tx(5) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','The Draw Area Tool is used to create masks over'...
                 'the desired data points on a graph. After using the',... 
                 'tool, the selected data points may either be',... 
                 'summed and have their center of pressure'...
                 'calculated and displayed, the points may be changed to',... 
                 'zero across all frames, and the Center of Pressure'...
                 'path may be recalculated across all frames.',' ',...
                 'Upon selecting the Draw Area Tool, the main figure',... 
                 'is made the current figure. The user''s cursor will'...
                 'become a crosshairs and may be used to draw the',... 
                 'points of a polygon with the final point closing',... 
                 'the polygon. (It is indicated the polygon may be'...
                 'closed when the user''s cursor becomes a circle when'... 
                 'hovered over the final (first) vertex. After closing',...
                 'the polygon off, the user may either double click the'...
                 'inside of the polygon or right click the inside and',... 
                 'select ''Create Mask''. ',' ',...
                 'Currently there is no built in function to highlight the masked',... 
                 'area after selection. The newly masked area may now be',...
                 'manipulated by either selecting the ''Change Selected to Zero''',...
                 'button or the ''Sum Selected Pressures'' button.'},...
                 'fontsize',10,'fontweight','bold');
HB.tx(6)= uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','The Change Selected to Zero button takes a',...
                 'currently masked area and turns the data',... 
                 'points at the internally selected',...
                 'coordinates to zero on all data frames.',' ',...
                 'The program will follow this selection up by regraphing the first frame'...
                 'of the main pressure data with the newly zeroed data graphed as well.',' ',...
                 'It is HIGHLY recommended to select the ''Recalculate CoP Data'' button after',...
                 'selecting the ''Change Selected to Zero'' button.',' ',... 
                 'The data frames may be navigated just as they were',...
                 'before and the Draw Area Tool may be used again.',...
                 'The ''Sum Selected Pressures'' and',...
                 '''Change Selected to Zero'' buttons may also be used again.'},...
                 'fontsize',11,'fontweight','bold');
HB.tx(7) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','The Sum Selected Pressure button takes a'...
                 'currently masked area and displays the sum'... 
                 'of the selected pressures on the MATLAB terminal.',' ',...
                 'The coordinates of the center of pressure of',... 
                 'exclusively the masked area are also shown'...
                 'on the terminal. A pink 6-pointed star will be'...
                 'displayed at these exact coordinates.',' ',...
                 'Numerous CoP stars may be visible at one time'...
                 'on a single frame. To clear the figure of these',...
                 'Center of Pressure stars, simply either change'...
                 'frames using the navigation tools or enter the same'...
                 'frame into the central navigation edit box and hit enter.',' ',...
                 'PLEASE TAKE NOTE: The numerical coordinates will NOT',... 
                 'match the graphical visual representation. Even though',...
                 'each cell on the pressure pad is 1/2cm x 1/2cm,',...
                 'MATLAB displays each box as 1cm x 1cm.',...
                 'The visual coordinates are multiplied by 2 to be graphed',...
                 'correctly visually. The coordinates printed in the terminal',...
                 'and from the export buttons show the correct non-multiplied',...
                 'values in cm.'},...
                 'fontsize',10,'fontweight','bold');
HB.tx(8) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','The Recalculate CoP button is meant to be used'...
                 'after the ''Change Selected to Zero'' button has been'...
                 'used. The path of the center of pressure will be'...
                 'recalculated and displayed on the screen.','The new current center of pressure'... 
                 'will be displayed as well.',' ','The new coordinates may then be exported'...
                 'using the ''Export New CoP Data'' button.'},...
                 'fontsize',12,'fontweight','bold');
HB.tx(9) = uicontrol('style','text',...
                 'units','pixels',...
                 'position',[15 20 395 420],...
                 'visible','off',...
                 'string',{' ','The navigation buttons are used to change the'...
                 'displayed frame of pressure data:',' ',... 
                 '[ << ] sets the current displayed frame to the first frame.',' ',...
                 '[ < ] decrements the current displayed frame by 1.',' ',...
                 'The edit box in the middle may be used to jump to a',...
                 'desired frame after typing in the frame number and',...
                 'striking the enter button.',' ',...
                 '[ > ] increments the current displayed frame by 1.',' ',...
                 '[ >> ] sets the current displayed frame to the last frame.',' ',...
                 ' ', 'Exceding the limits in either direction will bring up'...
                 'a warning box alerting the user of their mistake.',' ',...
                 'If Weight Text is turned on when a navigational request',...
                 'is made, Weight Text will be turned off so the',...
                 'regraphing is done in a timely manner.',... 
                 'It may be turned back on afterwards.'}',...
                 'fontsize',11,'fontweight','bold');
HB.tx(10)= uicontrol('style','text',...
                 'units','pixels',...
                 'position',[20 20 360 420],...
                 'visible','off',...
                 'string',{' ','The Export New CoP Data button is',...
                 'used to export a matrix of the coordinates of the center',...
                 'of pressure across all frames after having used'...
                 'the ''Change Selected to Zero'' button',...
                 ' and the ''Recalculate CoP Data'' button.',' ',...
                 'The Export Masked CoP Sequence button is',...
                 'used to export the newly calculated',... 
                 'coordinates of  the Center of Pressure line of',...
                 'the previously masked data after using',...
                 '''Sum Selected Pressures''.','The exported Masked CoP data corresponds',...
                 'only to the data WITHIN the last masked area.'...
                 ' ','Both include the corresponding forces of their respective areas.',...
                 ' ','The edit boxes next to both buttons are for'...
                 'naming the file(s) before they are exported.',...
                 'No extension is needed. The data will',... 
                 'automatically export as a .csv file.','The file location is the same location of',...
                 'the PressureGUI script.',' ',...
                 'The ''Create Clone'' button creates a clone of an existing CoP',...
                 '.csv file with the coordinates changed to be relative to the',... 
                 'Flashing LED at the bottom of the pressure pad. The clone',...
                 'will have the word ''_relative'' appended to the end of the file name.'},...
                 'fontsize',9,'fontweight','bold');
set(HB.tg(:),{'callback'},{{@tg_call,HB}})

function [] = tg_call(varargin)
[h,HB] = varargin{[1,3]};  

if get(h,'val')==0
    set(h,'val',1) 
end
switch h
    case HB.tg(1)
        set(HB.tg([2,3,4,5,6,7,8,9,10]),{'val'},{0})   
        set(HB.tx(1),{'visible'},{'on'})
        set([HB.tx(2),HB.tx(3),HB.tx(4),HB.tx(5),HB.tx(6),HB.tx(7),HB.tx(8),HB.tx(9),HB.tx(10)],{'visible'},{'off'})
    case HB.tg(2)
        set(HB.tg([1,3,4,5,6,7,8,9,10]),{'val'},{0})
        set(HB.tx(2),{'visible'},{'on'})
        set([HB.tx(1),HB.tx(3),HB.tx(4),HB.tx(5),HB.tx(6),HB.tx(7),HB.tx(8),HB.tx(9),HB.tx(10)],{'visible'},{'off'})
    case HB.tg(3)
        set(HB.tg([1,2,4,5,6,7,8,9,10]),'val',0)
        set(HB.tx(3),{'visible'},{'on'})
        set([HB.tx(1),HB.tx(2),HB.tx(4),HB.tx(5),HB.tx(6),HB.tx(7),HB.tx(8),HB.tx(9),HB.tx(10)],{'visible'},{'off'})
    case HB.tg(4)
        set(HB.tg([1,2,3,5,6,7,8,9,10]),{'val'},{0})
        set(HB.tx(4),'visible','on')
        set([HB.tx(1),HB.tx(2),HB.tx(3),HB.tx(5),HB.tx(6),HB.tx(7),HB.tx(8),HB.tx(9),HB.tx(10)],{'visible'},{'off'})     
    case HB.tg(5)
        set(HB.tg([1,2,3,4,6,7,8,9,10]),{'val'},{0})
        set(HB.tx(5),'visible','on')
        set([HB.tx(1),HB.tx(2),HB.tx(3),HB.tx(4),HB.tx(6),HB.tx(7),HB.tx(8),HB.tx(9),HB.tx(10)],{'visible'},{'off'})         
    case HB.tg(6)
        set(HB.tg([1,2,3,4,5,7,8,9,10]),{'val'},{0})
        set(HB.tx(6),'visible','on')
        set([HB.tx(1),HB.tx(2),HB.tx(3),HB.tx(4),HB.tx(5),HB.tx(7),HB.tx(8),HB.tx(9),HB.tx(10)],{'visible'},{'off'})
    case HB.tg(7)
        set(HB.tg([1,2,3,4,5,6,8,9,10]),'val',0)
        set(HB.tx(7),{'visible'},{'on'})
        set([HB.tx(1),HB.tx(2),HB.tx(3),HB.tx(4),HB.tx(5),HB.tx(6),HB.tx(8),HB.tx(9),HB.tx(10)],{'visible'},{'off'})
    case HB.tg(8)
        set(HB.tg([1,2,3,4,5,6,7,9,10]),{'val'},{0})
        set(HB.tx(8),'visible','on')
        set([HB.tx(1),HB.tx(2),HB.tx(3),HB.tx(4),HB.tx(5),HB.tx(6),HB.tx(7),HB.tx(9),HB.tx(10)],{'visible'},{'off'})     
    case HB.tg(9)
        set(HB.tg([1,2,3,4,5,6,7,8,10]),{'val'},{0})
        set(HB.tx(9),'visible','on')
        set([HB.tx(1),HB.tx(2),HB.tx(3),HB.tx(4),HB.tx(5),HB.tx(6),HB.tx(7),HB.tx(8),HB.tx(10)],{'visible'},{'off'})         
    case HB.tg(10)
        set(HB.tg([1,2,3,4,5,6,7,8,9]),{'val'},{0})
        set(HB.tx(10),'visible','on')
        set([HB.tx(1),HB.tx(2),HB.tx(3),HB.tx(4),HB.tx(5),HB.tx(6),HB.tx(7),HB.tx(8),HB.tx(9)],{'visible'},{'off'})
end
end

end